# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['scripts\\kivy_desktop_app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('landing', 'landing'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'app.main',
        'app.api.routes.health',
        'app.api.routes.orders',
        'app.api.routes.portfolio',
        'app.api.routes.strategy',
        'app.api.routes.risk',
        'app.api.routes.market',
        'app.api.routes.waitlist',
        'app.api.routes.cache',
        'uvicorn',
        'fastapi',
        'pydantic',
        'pydantic_settings',
        'kivy',
        'kivy.core.window.window_sdl2',
        'kivy.uix.boxlayout',
        'kivy.uix.button',
        'kivy.uix.textinput',
        'kivy.uix.label',
        'kivy.lang',
        'kivy.app',
        'kivy.clock',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'numpy',
        'pandas',
        'tensorflow',
        'torch',
        'scipy',
        'sklearn',
        'kivy.lib.gstplayer',
        'kivy.core.spelling.spelling_enchant',
        'enchant',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ai_trading_kivy_desktop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
