"""initial

Revision ID: f5b534ab38b6
Revises: 
Create Date: 2026-02-20 10:33:19.831209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b534ab38b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('final_balance', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('profitable_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('avg_profit', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_strategy_name'), 'backtest_results', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_backtest_results_timestamp'), 'backtest_results', ['timestamp'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prediction', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_timestamp_symbol', 'ml_predictions', ['timestamp', 'symbol'], unique=False)
    op.create_index(op.f('ix_ml_predictions_symbol'), 'ml_predictions', ['symbol'], unique=False)
    op.create_index(op.f('ix_ml_predictions_timestamp'), 'ml_predictions', ['timestamp'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_trained', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('filepath', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('confusion_matrix', sa.Text(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('test_samples', sa.Integer(), nullable=True),
    sa.Column('training_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_model_name'), 'model_performance', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_performance_timestamp'), 'model_performance', ['timestamp'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'symbol', name='uix_price_timestamp_symbol')
    )
    op.create_index('idx_price_timestamp_symbol', 'price_history', ['timestamp', 'symbol'], unique=False)
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_symbol'), 'trading_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_trading_signals_timestamp'), 'trading_signals', ['timestamp'], unique=False)
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_symbol'), 'training_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_training_data_timestamp'), 'training_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_data_timestamp'), table_name='training_data')
    op.drop_index(op.f('ix_training_data_symbol'), table_name='training_data')
    op.drop_table('training_data')
    op.drop_index(op.f('ix_trading_signals_timestamp'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_symbol'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_index('idx_price_timestamp_symbol', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_model_performance_timestamp'), table_name='model_performance')
    op.drop_index(op.f('ix_model_performance_model_name'), table_name='model_performance')
    op.drop_table('model_performance')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_ml_predictions_timestamp'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_symbol'), table_name='ml_predictions')
    op.drop_index('idx_pred_timestamp_symbol', table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_backtest_results_timestamp'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_strategy_name'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
